### PR TITLE
fastn tutor part tres

### PR DESCRIPTION
**Pull request by amitu**
[Docs](https://github.com/orgs/fastn-stack/discussions/1414) 

- [x] font issue

### CODE REVIEW

**Comment by Arpita-Jaiswal** [comment]
@amitu fonts are not working

**Comment by amitu** [comment]
@Arpita-Jaiswal its quite odd, the tests are passing on my machine but failing on Github CI.

**Comment by Arpita-Jaiswal** [comment]
Blocked on roles/font's not working

**Comment by Arpita-Jaiswal** [comment]
@amitu I think font is fixed. I am building fastn.com. Lets see.

**Comment by amitu** [comment]
@Arpita-Jaiswal awesome! Thanks :-)

**Comment by amitu** [comment]
@Arpita-Jaiswal how do we test this further? I want to merge it but it was a drastic PR. One option we just merge it, fastn.com seems to be working (or we will soon find out if something is broken on fastn.com).

**Comment by Arpita-Jaiswal** [comment]
@amitu `fastn build` is still failing for font, `fastn serve` is now working

**Review by Arpita-Jaiswal — APPROVED** [review]

**Pull request merged**
