### PR TITLE
Added Vmin and Vmax Lengths

### PR DESCRIPTION
**Pull request by theharshsingh**
Hey team, I've made some changes in this pull request:

- Added support for Vmin and Vmax lengths by adapting existing code for vw and vh lengths.
- Refactored the utils.ts file, replacing string concatenations with string interpolations.

### CODE REVIEW

**Comment by amitu** [comment]
@theharshsingh, looks good. 

One request: can you also create a PR against https://github.com/fastn-stack/fastn.com, with some docs and examples, so we merge both docs and code changes together?

**Comment by theharshsingh** [comment]
> @theharshsingh, looks good.
> 
> One request: can you also create a PR against https://github.com/fastn-stack/fastn.com, with some docs and examples, so we merge both docs and code changes together?

Absolutely, I have already created a pull request against https://github.com/fastn-stack/fastn.com. It includes the necessary documentation and examples to accompany the code changes.

**Comment by amitu** [comment]
https://github.com/fastn-stack/fastn.com/pull/179

**Review by Arpita-Jaiswal — APPROVED** [review]

**Comment by Arpita-Jaiswal** [comment]
@theharshsingh Can you please resolve the conflict?

**Pull request merged**
