### PR TITLE
removing controller stuff and .d files from release

### PR DESCRIPTION
**Pull request by amitu**

### CODE REVIEW

**Comment by amitu** [comment]
@harshdoesdev can you take a look at this, and merge this after https://github.com/fastn-stack/fastn.com/pull/522 is merged and deployed. No need to build controller binaries also as they are not supported.

**Review by harshdoesdev — APPROVED** [review]
Looks good! tested it on a fork, working as expected. Merging it.

**Comment by harshdoesdev** [comment]
@amitu it seems like there is some issue related to fbt test cases. the release was created on my forked PR, but the test failed.

**Comment by amitu** [comment]
My latest PR got merged, and it had error. I had enabled auto merge assuming it will auto merge when all criteria's (approval and test passing) is met it will merge but github merged only after approval criteria got met. 

Could be that.

**Pull request merged**
