### PR TITLE
take record args for fetch options in ftd.fetch

### PR DESCRIPTION
**Pull request by siddhantk232**
### Example

```
-- ftd.http-options opts:
redirect: manual ;; only follow | manual | error     default: manual
method: GET  ;; only GET | POST                      default: GET
fastn-module: test-multiauth

-- ftd.column:
padding.px: 16

-- ftd.text: Login
padding-top.px: 16
$on-click$: $submit(opts = $opts)

-- end: ftd.column

-- void submit(opts):
ftd.http-options opts:

ftd.http(
    "/-/auth/login/?provider=emailpassword",
    opts,
    ("username", "test"),
    ("password", "example"),
)
```

### CODE REVIEW

**Comment by amitu** [comment]
How did you format the code? Maybe we should add formatter as CI, the way we do for Rust to achieve consistent formatting of JS files.

**Comment by amitu** [comment]
We have to move the definition of the record into ftd crate, with name `ftd.http-options` or something.

**Comment by amitu** [comment]
Instead of `string redirect` we should have an `or-type`, `ftd.http-redirect-behaviour` or something.

**Comment by amitu** [comment]
Method should also be an `or-type`.

**Comment by siddhantk232** [comment]
> How did you format the code? Maybe we should add formatter as CI, the way we do for Rust to achieve consistent formatting of JS files.

```js
prettier --write --tab-width 4 fastn-js/js/ftd.js
```

**Review by amitu — APPROVED** [review]

**Pull request merged**
