### PR TITLE
minor fix: error on kw-arg values other than string

### PR DESCRIPTION
**Pull request by harshdoesdev**

### CODE REVIEW

**Comment by amitu** [comment]
@harshdoesdev add test case for non string values:

```ftd
-- component foo:
integer kw-args data:

-- end: foo
```

Is this supported? If so write a test. Also write Rust test to extract the value of `data` from ftd document.

**Review by Heulitig — APPROVED** [review]

**Comment by harshdoesdev** [comment]
> @harshdoesdev add test case for non string values:
> 
> ```
> -- component foo:
> integer kw-args data:
> 
> -- end: foo
> ```
> 
> Is this supported? If so write a test. Also write Rust test to extract the value of `data` from ftd document.

This syntax is not yet supported, only string values are supported.

**Comment by amitu** [comment]
@harshdoesdev is there a test for extracting the data in Rust? If not create it.

**Comment by harshdoesdev** [comment]
> @harshdoesdev is there a test for extracting the data in Rust? If not create it.

I have written an interpreter test for this: https://github.com/fastn-stack/fastn/pull/1793.

**Comment by amitu** [comment]
@harshdoesdev I want the Rust code snippet someone has to use to extract data.

**Comment by harshdoesdev** [comment]
> @harshdoesdev I want the Rust code snippet someone has to use to extract data.

Got it.

**Comment by harshdoesdev** [comment]
> @harshdoesdev I want the Rust code snippet someone has to use to extract data.

@amitu I have added Rust tests for the `kw-args` feature and reading its values: https://github.com/fastn-stack/fastn/pull/1796

**Pull request merged**
