### PR TITLE
mask-image property added and code refactor

### PR DESCRIPTION
**Pull request by harshdoesdev**
added the [`mask-image`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image) property in Common properties. The mask hides an element (partially or fully) by masking or clipping the image at specific points.

Example:
```ftd
-- ftd.container:
background.solid: red
mask.image: https://mdn.github.io/css-examples/masking/star.svg
width.fixed.px: 300
height.fixed.px: 300
```

Output:
image

### CODE REVIEW

**Comment by amitu** [comment]
@harshdoesdev, @Heulitig lets ensure https://github.com/fastn-stack/fastn/issues/1390 is solved with this PR.

**Comment by harshdoesdev** [comment]
@amitu, the mask-image property has been implemented. Please verify whether this resolves the issue at https://github.com/fastn-stack/fastn/issues/1390.

**Comment by amitu** [comment]
@harshdoesdev show a demo that looks like this https://codepen.io/noahblon/pen/PovZva

**Comment by harshdoesdev** [comment]
@Heulitig  I have added all of the required mask properties, but when I am running the tests, I am getting stack-overflow errors (originating from a totally unrelated test, the mask test is working perfectly fine when ran individually by providing the path argument)

**Pull request merged**
